spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brackets?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-idle: 100
    max-wait: 10000
    validation-queury: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 27800
    test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  servlet:
    multipart:
      max-file-size: 700MB
      max-request-size: 700MB
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /brackets

feign:
  hystrix:
    enabled: false
console:
  log:
    level: INFO
logging:
  config: classpath:logback-dev.xml